spring:
  datasource:
    password: Us8gmGeWGx9S
    url: jdbc:postgresql://frog01.mikr.us:40350/pwypisy
    username: pwypisy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect